# Generated by Django 3.1.4 on 2021-01-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='page_title',
            field=models.CharField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
