# Generated by Django 3.1.4 on 2021-03-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='package',
            name='category',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ManyToManyField(related_name='packages', to='holidays.Category'),
        ),
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='holidays.country'),
        ),
        migrations.AlterField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(related_name='packages', to='flights.Flight'),
        ),
    ]
