# Generated by Django 3.1.4 on 2021-01-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20210121_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('page_title', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('image_url', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='country',
            name='page_title',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holidays.package'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.region'),
        ),
    ]
