# Generated by Django 3.1.4 on 2021-03-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('holidays', '0003_auto_20210310_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='categories',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='holidays.category'),
        ),
        migrations.AddField(
            model_name='package',
            name='offer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='packages', to='flights.Flight'),
        ),
    ]
