# Generated by Django 3.1.4 on 2021-01-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20210121_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.region'),
        ),
    ]
