# Generated by Django 3.1.4 on 2021-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_auto_20210121_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
