# Generated by Django 3.1.4 on 2021-03-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_auto_20210324_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ('day',), 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.CharField(max_length=254),
        ),
    ]
