# Generated by Django 3.1.4 on 2021-01-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_auto_20210126_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='layover',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='layover_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
