# Generated by Django 3.1.4 on 2021-03-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0008_auto_20210327_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': 'Itineraries'},
        ),
    ]
