# Generated by Django 3.1.4 on 2021-03-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0010_auto_20210327_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='package',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='holidays.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='accomodation',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
