# Generated by Django 3.1.4 on 2021-01-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0011_auto_20210130_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='layover_duration',
        ),
    ]
