# Generated by Django 3.1.4 on 2021-02-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('holidays', '0012_remove_flight_layover_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='extras',
            field=models.ManyToManyField(related_name='packages', to='extras.Extra'),
        ),
    ]
