# Generated by Django 3.1.4 on 2021-05-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0012_auto_20210331_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('id',), 'verbose_name_plural': 'Activities'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('title', models.CharField(max_length=254)),
                ('review', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='holidays.package')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
