# Generated by Django 3.1.4 on 2021-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('flights', '0001_initial'),
        ('checkout', '0014_auto_20210305_1753'),
        ('holidays', '0013_package_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.CharField(choices=[('', 'Day'), ('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6'), ('7', 'Day 7'), ('8', 'Day 8'), ('9', 'Day 9'), ('10', 'Day 10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='packages', to='holidays.Activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='packages', to='extras.Extra'),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.ManyToManyField(related_name='packages', to='holidays.Feature'),
        ),
        migrations.RemoveField(
            model_name='package',
            name='outbound_flight',
        ),
        migrations.AddField(
            model_name='package',
            name='outbound_flight',
            field=models.ManyToManyField(blank=True, related_name='outbound_flight_packages', to='flights.Flight'),
        ),
        migrations.RemoveField(
            model_name='package',
            name='return_flight',
        ),
        migrations.AddField(
            model_name='package',
            name='return_flight',
            field=models.ManyToManyField(blank=True, related_name='inbound_flight_packages', to='flights.Flight'),
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
