# Generated by Django 3.1.4 on 2021-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0013_auto_20210503_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
