# Generated by Django 3.1.4 on 2021-05-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0014_review_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='accomodation',
        ),
        migrations.AlterField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
