# Generated by Django 3.1.4 on 2021-03-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('holidays', '0014_auto_20210305_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='outbound_flight',
        ),
        migrations.RemoveField(
            model_name='package',
            name='return_flight',
        ),
        migrations.AddField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='packages', to='flights.Flight'),
        ),
    ]
