# Generated by Django 3.1.3 on 2021-06-08 16:34

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20210521_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
