# Generated by Django 3.1.3 on 2021-06-08 22:40

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_auto_20210608_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
