# Generated by Django 3.1.4 on 2021-05-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Contact',
        ),
    ]
