# Generated by Django 3.1.4 on 2021-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210504_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default="2021-05-05"),
            preserve_default=False,
        ),
    ]
