# Generated by Django 3.1.4 on 2021-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('', 'Subject *'), ('Holiday Information', 'Holiday Information'), ('Offers', 'Offers'), ('Bookings', 'Bookings'), ('General Enquiries', 'General Enquiries'), ('Other', 'Other')], max_length=254),
        ),
    ]
