# Generated by Django 3.1.4 on 2021-03-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpassenger',
            name='passport_number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
