# Generated by Django 3.1.4 on 2021-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210317_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total',
            new_name='grand_total',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='return_date',
            field=models.DateField(default='2021-08-01'),
            preserve_default=False,
        ),
    ]
