# Generated by Django 3.1.3 on 2021-05-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_duration'),
        ('holidays', '0015_auto_20210517_2151'),
        ('booking', '0003_auto_20210515_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default='2021-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='outbound_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_flight', to='flights.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default='2021-2-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='return_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_flight', to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='coupon',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingextra',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BookingPackage',
        ),
    ]
