# Generated by Django 3.1.3 on 2021-05-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0015_auto_20210517_2151'),
        ('booking', '0004_auto_20210524_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.package'),
        ),
    ]
