# Generated by Django 3.1.3 on 2021-06-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210525_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
