# Generated by Django 3.1.3 on 2021-06-10 19:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210603_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=20, region=None),
        ),
    ]
