# Generated by Django 3.1.4 on 2021-01-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagebooking',
            old_name='Package',
            new_name='package',
        ),
    ]
