# Generated by Django 3.1.4 on 2021-01-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210131_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagebooking',
            old_name='package_total',
            new_name='total',
        ),
    ]
