# Generated by Django 3.1.4 on 2021-02-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210222_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingPassengers',
            new_name='BookingPassenger',
        ),
        migrations.AlterField(
            model_name='bookingextra',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_extras', to='checkout.booking'),
        ),
    ]
