# Generated by Django 3.1.4 on 2021-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20210223_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
