# Generated by Django 3.1.4 on 2021-03-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('checkout', '0013_auto_20210224_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpackage',
            name='outbound_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_outbound_flight', to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='bookingpackage',
            name='return_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_inbound_flight', to='flights.flight'),
        ),
    ]
