# Generated by Django 3.1.4 on 2021-03-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20210305_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingextra',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingextra',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='outbound_flight',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='return_flight',
        ),
        migrations.RemoveField(
            model_name='bookingpassenger',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingExtra',
        ),
        migrations.DeleteModel(
            name='BookingPackage',
        ),
        migrations.DeleteModel(
            name='BookingPassenger',
        ),
    ]
