# Generated by Django 3.1.4 on 2021-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('origin', models.CharField(max_length=254)),
                ('destination', models.CharField(max_length=254)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('layover', models.CharField(blank=True, max_length=254, null=True)),
                ('baggage', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
