# Generated by Django 3.1.3 on 2021-05-23 19:07

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20210517_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_time_zone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
            preserve_default=False,
        ),
    ]
