# Generated by Django 3.1.3 on 2021-05-24 13:06

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20210523_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(default=timedelta(seconds=0)),
            preserve_default=False,
        ),
    ]
